version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
resolve_s3 = true
confirm_changeset = false


[staging.global.parameters]
region = "us-east-1"
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
